### PR TITLE
Lut unit test case fix

### PR DESCRIPTION
**Pull request by r-abishek**
@kiritigowda @paveltc This is a one liner fix for output in unit test for lut host

### CODE REVIEW

**Comment by r-abishek** [comment]
@snehaa8 Can you take a look?

**Comment by snehaa8** [comment]
@paveltc 
Fixed issue with dumping outputs for above failing testcases, can you please recheck.

**Comment by paveltc** [comment]
@snehaa8 @r-abishek @kiritigowda Just ran the tests. Everything looks fixed. This is good to merge.

**Comment by r-abishek** [comment]
Thanks @paveltc! @kiritigowda Could you merge this one?

**Pull request merged**
