### PR TITLE
RPP Boost Replacement

### PR DESCRIPTION
**Pull request by hansely**
Removed the boost dependency from rpp
Updated the c++ version requirements from 14 to 17
Deleted the files that are outdated

### CODE REVIEW

**Review by r-abishek — COMMENTED** [review]
@hansely The change to C++17, with boost to standard filesystem looks good - boost was used in the test suite too for recursively finding files, I see that's been changed too. @paveltc We need to verify HIP, OCL, CPU-only builds for RPP. And then we need to run the latest test_suite/HIP and test_suite/HOST unit tests for say brightness to verify.

**Review by r-abishek — APPROVED** [review]

**Comment by kiritigowda** [comment]
@hansely can you resolve conflicts?

**Comment by hansely** [comment]
@kiritigowda conflicts resolved

**Comment by kiritigowda** [comment]
@hansely  this PR is failing for OCL backend. Need to verify the OCL build

**Pull request merged**
