### PR TITLE
RPP Test Suite CI addition

### PR DESCRIPTION
**Pull request by r-abishek**
@kiritigowda This PR:
- Changes to C++ 17 for test suite
- C++ 17 forces return check on [[nodiscard]] API. So, added checks to prevent warnings
- Added necessary latest Tensor Python based tests in Cmake for HOST and HIP test suite.
- Adds clarity in display of final results of tests

### CODE REVIEW

**Comment by r-abishek** [comment]
@kiritigowda Taken ideas from your PR on what parts work, and made changes as appropriate in other places.
I am now able to run the python script from anywhere outside too, giving expected outputs. 

Verified:
- unit test mode,
-  QA test mode
- performance test mode
- For hip, verified with/without rocprof profiling modes

Could you check if this works from CI perspective?

**Comment by kiritigowda** [comment]
@r-abishek - merge this PR - https://github.com/r-abishek/rpp/pull/185 into this branch will add full testing functionality to TOT CTest

**Comment by kiritigowda** [comment]
Run `make test ARGS="-VV"` for detailed output - once the https://github.com/r-abishek/rpp/pull/185 is merged

```
make test
Running tests...
Test project /home/kiriti/develop/rpp-kiriti/build
      Start  1: rpp_cpu_test_u08_01
 1/26 Test  #1: rpp_cpu_test_u08_01 ..............   Passed   15.10 sec
      Start  2: rpp_cpu_test_u08_02
 2/26 Test  #2: rpp_cpu_test_u08_02 ..............   Passed    0.09 sec
      Start  3: rpp_cpu_test_u08_03
 3/26 Test  #3: rpp_cpu_test_u08_03 ..............   Passed    0.09 sec
      Start  4: rpp_cpu_test_u08_04
 4/26 Test  #4: rpp_cpu_test_u08_04 ..............   Passed    0.07 sec
      Start  5: rpp_cpu_test_u08_05
 5/26 Test  #5: rpp_cpu_test_u08_05 ..............   Passed    0.09 sec
      Start  6: rpp_cpu_test_u08_06
 6/26 Test  #6: rpp_cpu_test_u08_06 ..............   Passed    0.07 sec
      Start  7: rpp_cpu_test_u08_07
 7/26 Test  #7: rpp_cpu_test_u08_07 ..............   Passed    0.07 sec
      Start  8: rpp_cpu_test_u08_08
 8/26 Test  #8: rpp_cpu_test_u08_08 ..............   Passed    0.07 sec
      Start  9: rpp_cpu_test_u08_09
 9/26 Test  #9: rpp_cpu_test_u08_09 ..............   Passed    0.07 sec
      Start 10: rpp_cpu_test_u08_11
10/26 Test #10: rpp_cpu_test_u08_11 ..............   Passed    0.09 sec
      Start 11: rpp_cpu_test_u08_12
11/26 Test #11: rpp_cpu_test_u08_12 ..............   Passed    0.07 sec
      Start 12: rpp_cpu_test_f16_13
12/26 Test #12: rpp_cpu_test_f16_13 ..............   Passed    0.06 sec
      Start 13: rpp_cpu_test_f32_14
13/26 Test #13: rpp_cpu_test_f32_14 ..............   Passed    0.07 sec
      Start 14: rpp_cpu_test_i08_15
14/26 Test #14: rpp_cpu_test_i08_15 ..............   Passed    0.07 sec
      Start 15: rpp_hip_test_u08_01
15/26 Test #15: rpp_hip_test_u08_01 ..............   Passed   51.39 sec
      Start 16: rpp_hip_test_u08_02
16/26 Test #16: rpp_hip_test_u08_02 ..............   Passed    0.43 sec
      Start 17: rpp_hip_test_u08_03
17/26 Test #17: rpp_hip_test_u08_03 ..............   Passed    0.38 sec
      Start 18: rpp_hip_test_u08_04
18/26 Test #18: rpp_hip_test_u08_04 ..............   Passed    0.40 sec
      Start 19: rpp_hip_test_u08_05
19/26 Test #19: rpp_hip_test_u08_05 ..............   Passed    0.41 sec
      Start 20: rpp_hip_test_u08_06
20/26 Test #20: rpp_hip_test_u08_06 ..............   Passed    0.35 sec
      Start 21: rpp_hip_test_u08_07
21/26 Test #21: rpp_hip_test_u08_07 ..............   Passed    0.35 sec
      Start 22: rpp_hip_test_f16_08
22/26 Test #22: rpp_hip_test_f16_08 ..............   Passed    0.45 sec
      Start 23: rpp_hip_test_f32_09
23/26 Test #23: rpp_hip_test_f32_09 ..............   Passed    0.36 sec
      Start 24: rpp_hip_test_i08_10
24/26 Test #24: rpp_hip_test_i08_10 ..............   Passed    0.36 sec
      Start 25: rpp_qa_tests_host
25/26 Test #25: rpp_qa_tests_host ................   Passed   20.87 sec
      Start 26: rpp_qa_tests_hip
26/26 Test #26: rpp_qa_tests_hip .................   Passed   55.94 sec

100% tests passed, 0 tests failed out of 26

Total Test time (real) = 147.78 sec

```

**Comment by kiritigowda** [comment]
Merged #242

**Pull request closed without merging**
