### PR TITLE
Crop border patch issue fix and crop mirror normalize issue fix

### PR DESCRIPTION
**Pull request by LokeshBonta**

### CODE REVIEW

**Comment by kiritigowda** [comment]
@LokeshBonta can you sync to TOT.

**Comment by LokeshBonta** [comment]
@kiritigowda
I have synced to TOT.
Can you please tell me what is abbreviation of TOT? (sorry for not being aware of :-))

**Comment by kiritigowda** [comment]
@LokeshBonta TOT (Top of Tree) Master. Now the CI is building on this PR with the TOT merge.

**Comment by LokeshBonta** [comment]
@kiritigowda 
Thank you :)

**Pull request merged**
