### PR TITLE
CMake Downgrade

### PR DESCRIPTION
**Pull request by kiritigowda**
CMake Version 3.15 to 3.5

### CODE REVIEW

**Comment by LakshmiKumar23** [comment]
@kiritigowda Tested this PR yesterday and ran image_augmentation app on it. Ready to be merged

**Comment by kiritigowda** [comment]
@rrawther and @LakshmiKumar23 this PR include #19 and fix all the conflicts.

**Comment by kiritigowda** [comment]
````
 cmake ../rpp/
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
amd_rpp - 0.2
cmake minimum version required: 3.5
cmake version found: 3.10.2
-- Clang tidy not found
-- Clang tidy checks: *,-cert-env33-c,-android-cloexec-fopen,-cert-msc30-c,-cert-msc50-cpp,-clang-analyzer-alpha.core.CastToStruct,-clang-analyzer-optin.performance.Padding,-clang-diagnostic-deprecated-declarations,-clang-diagnostic-extern-c-compat,-clang-diagnostic-unused-command-line-argument,-cppcoreguidelines-pro-bounds-array-to-pointer-decay,-cppcoreguidelines-pro-bounds-constant-array-index,-cppcoreguidelines-pro-bounds-pointer-arithmetic,-cppcoreguidelines-pro-type-member-init,-cppcoreguidelines-pro-type-reinterpret-cast,-cppcoreguidelines-pro-type-union-access,-cppcoreguidelines-pro-type-vararg,-cppcoreguidelines-special-member-functions,-fuchsia-*,-google-explicit-constructor,-google-readability-braces-around-statements,-google-readability-todo,-google-runtime-int,-google-runtime-references,-hicpp-braces-around-statements,-hicpp-explicit-conversions,-hicpp-no-array-decay,-hicpp-signed-bitwise,-hicpp-special-member-functions,-hicpp-use-equals-default,-hicpp-use-override,-llvm-header-guard,-llvm-include-order,-misc-misplaced-const,-modernize-pass-by-value,-modernize-use-default-member-init,-modernize-use-equals-default,-modernize-use-transparent-functors,-performance-unnecessary-value-param,-readability-braces-around-statements,-readability-else-after-return,-readability-named-parameter,-hicpp-use-auto,-modernize-use-auto,-cppcoreguidelines-avoid-magic-numbers,-readability-magic-numbers,-cppcoreguidelines-macro-usage,-misc-non-private-member-variables-in-classes,-cppcoreguidelines-non-private-member-variables-in-classes,-readability-isolate-declaration,-cppcoreguidelines-avoid-c-arrays,-hicpp-avoid-c-arrays,-modernize-avoid-c-arrays,-readability-uppercase-literal-suffix,-hicpp-uppercase-literal-suffix,-cert-msc32-c,-cert-msc51-cpp,-bugprone-exception-escape
-- Found OPENCL: /opt/rocm/opencl/lib/x86_64/libOpenCL.so  
-- extractkernel found: /opt/rocm/bin/extractkernel
-- AMDGCN assembler: MIOPEN_AMDGCN_ASSEMBLER-NOTFOUND
Add Custome Command
OPenCL incude directories are /opt/rocm/opencl/include;/home/kiriti/develop/rpp/rpp/src/include/cl/
-- amd_rpp built with ENABLE_SIMD_INTRINSICS
-- Boost version: 1.64.0
-- Found the following Boost libraries:
--   filesystem
--   system
-- Found OpenMP_C: -fopenmp (found version "4.5") 
-- Found OpenMP_CXX: -fopenmp (found version "4.5") 
-- Found OpenMP: TRUE (found version "4.5")  
-- Configuring done
-- Generating done
-- Build files have been written to: /home/kiriti/develop/rpp/build
kiriti@simon:~/develop/rpp/build$ make
Scanning dependencies of target addkernels
[  2%] Building CXX object addkernels/CMakeFiles/addkernels.dir/include_inliner.cpp.o
[  4%] Building CXX object addkernels/CMakeFiles/addkernels.dir/addkernels.cpp.o
[  6%] Linking CXX executable addkernels
[  6%] Built target addkernels
[  8%] Inlining Rpp HIP kernel includes
[ 10%] Inlining Rpp kernels
Scanning dependencies of target modules
[ 13%] Building CXX object src/modules/CMakeFiles/modules.dir/binary_cache.cpp.o
[ 15%] Building CXX object src/modules/CMakeFiles/modules.dir/kernel_cache.cpp.o
[ 17%] Building CXX object src/modules/CMakeFiles/modules.dir/logger.cpp.o
[ 19%] Building CXX object src/modules/CMakeFiles/modules.dir/md5.cpp.o
[ 21%] Building CXX object src/modules/CMakeFiles/modules.dir/rppi_arithmetic_operations.cpp.o
[ 23%] Building CXX object src/modules/CMakeFiles/modules.dir/rppi_color_model_conversions.cpp.o
[ 26%] Building CXX object src/modules/CMakeFiles/modules.dir/rppi_computer_vision.cpp.o
[ 28%] Building CXX object src/modules/CMakeFiles/modules.dir/rppi_filter_operations.cpp.o
[ 30%] Building CXX object src/modules/CMakeFiles/modules.dir/rppi_fused_functions.cpp.o
[ 32%] Building CXX object src/modules/CMakeFiles/modules.dir/rppi_geometry_transforms.cpp.o
[ 34%] Building CXX object src/modules/CMakeFiles/modules.dir/rppi_image_augmentations.cpp.o
[ 36%] Building CXX object src/modules/CMakeFiles/modules.dir/rppi_logical_operations.cpp.o
[ 39%] Building CXX object src/modules/CMakeFiles/modules.dir/rppi_morphological_operations.cpp.o
[ 41%] Building CXX object src/modules/CMakeFiles/modules.dir/rppi_statistical_operations.cpp.o
[ 43%] Building CXX object src/modules/CMakeFiles/modules.dir/rppi_utilities.cpp.o
[ 45%] Building CXX object src/modules/CMakeFiles/modules.dir/kernel.cpp.o
[ 47%] Building CXX object src/modules/CMakeFiles/modules.dir/kernel_includes.cpp.o
[ 50%] Building CXX object src/modules/CMakeFiles/modules.dir/cl/cl_arithmetic_operations.cpp.o
[ 52%] Building CXX object src/modules/CMakeFiles/modules.dir/cl/cl_color_model_conversions.cpp.o
[ 54%] Building CXX object src/modules/CMakeFiles/modules.dir/cl/cl_computer_vision.cpp.o
[ 56%] Building CXX object src/modules/CMakeFiles/modules.dir/cl/cl_filter_functions.cpp.o
[ 58%] Building CXX object src/modules/CMakeFiles/modules.dir/cl/cl_fused_functions.cpp.o
[ 60%] Building CXX object src/modules/CMakeFiles/modules.dir/cl/cl_geometry_transforms.cpp.o
[ 63%] Building CXX object src/modules/CMakeFiles/modules.dir/cl/cl_image_augmentations.cpp.o
[ 65%] Building CXX object src/modules/CMakeFiles/modules.dir/cl/cl_logical_operations.cpp.o
[ 67%] Building CXX object src/modules/CMakeFiles/modules.dir/cl/cl_morphological_transforms.cpp.o
[ 69%] Building CXX object src/modules/CMakeFiles/modules.dir/cl/cl_statistical_operations.cpp.o
[ 71%] Building CXX object src/modules/CMakeFiles/modules.dir/cl/cl_utilities.cpp.o
[ 73%] Building CXX object src/modules/CMakeFiles/modules.dir/cl/cl_vision.cpp.o
[ 76%] Building CXX object src/modules/CMakeFiles/modules.dir/cl/clhelper.cpp.o
[ 78%] Building CXX object src/modules/CMakeFiles/modules.dir/cl/gcn_asm_utils.cpp.o
[ 80%] Building CXX object src/modules/CMakeFiles/modules.dir/cl/handle_api.cpp.o
[ 82%] Building CXX object src/modules/CMakeFiles/modules.dir/cl/handleocl.cpp.o
[ 84%] Building CXX object src/modules/CMakeFiles/modules.dir/cl/hip_build_utils.cpp.o
[ 86%] Building CXX object src/modules/CMakeFiles/modules.dir/cl/load_file.cpp.o
[ 89%] Building CXX object src/modules/CMakeFiles/modules.dir/cl/ocl_kernel.cpp.o
[ 91%] Building CXX object src/modules/CMakeFiles/modules.dir/cl/oclerrors.cpp.o
[ 93%] Building CXX object src/modules/CMakeFiles/modules.dir/cl/temp_file.cpp.o
[ 95%] Building CXX object src/modules/CMakeFiles/modules.dir/cl/tmp_dir.cpp.o
[ 97%] Building CXX object src/modules/CMakeFiles/modules.dir/cl/utilocl.cpp.o
[ 97%] Built target modules
Scanning dependencies of target amd_rpp
[100%] Linking CXX shared library libamd_rpp.so
[100%] Built target amd_rpp

````

**Comment by kiritigowda** [comment]
Builds & installs
```
sudo make install
[  6%] Built target addkernels
[ 97%] Built target modules
[100%] Built target amd_rpp
Install the project...
-- Install configuration: ""
-- Up-to-date: /opt/rocm/rpp/lib/libamd_rpp.so
-- Up-to-date: /opt/rocm/rpp//include
-- Up-to-date: /opt/rocm/rpp//include/rppi_image_augmentations.h
-- Up-to-date: /opt/rocm/rpp//include/rppi_logical_operations.h
-- Up-to-date: /opt/rocm/rpp//include/version.h
-- Up-to-date: /opt/rocm/rpp//include/rppi_statistical_operations.h
-- Up-to-date: /opt/rocm/rpp//include/rppi_support_functions.h
-- Up-to-date: /opt/rocm/rpp//include/rppcore.h
-- Up-to-date: /opt/rocm/rpp//include/rppdefs.h
-- Up-to-date: /opt/rocm/rpp//include/rpp
-- Up-to-date: /opt/rocm/rpp//include/rpp/version.h
-- Up-to-date: /opt/rocm/rpp//include/rpp/export.h
-- Up-to-date: /opt/rocm/rpp//include/rpp/rpp.h
-- Up-to-date: /opt/rocm/rpp//include/rpp/config.h
-- Up-to-date: /opt/rocm/rpp//include/rppi.h
-- Up-to-date: /opt/rocm/rpp//include/rppi_fused_functions.h
-- Up-to-date: /opt/rocm/rpp//include/rppi_geometry_transforms.h
-- Up-to-date: /opt/rocm/rpp//include/rppi_color_model_conversions.h
-- Up-to-date: /opt/rocm/rpp//include/rppi_computer_vision.h
-- Up-to-date: /opt/rocm/rpp//include/export.h
-- Up-to-date: /opt/rocm/rpp//include/rppi_filter_operations.h
-- Up-to-date: /opt/rocm/rpp//include/rppversion.h
-- Up-to-date: /opt/rocm/rpp//include/rppi_arithmetic_operations.h
-- Up-to-date: /opt/rocm/rpp//include/rppi_morphological_transforms.h
-- Up-to-date: /opt/rocm/rpp//include/rpp.h
-- Up-to-date: /opt/rocm/rpp//include/config.h
```

**Pull request merged**
