### PR TITLE
Develop - Merge to TOT Master

### PR DESCRIPTION
**Pull request by kiritigowda**

### CODE REVIEW

**Review by rrawther — APPROVED** [review]
@paveltc to run tests on this

**Comment by paveltc** [comment]
@rrawther Do you know what changes are expected from this PR? Anything actually touching the RPP kernels and their functionality?

**Comment by paveltc** [comment]
@kiritigowda But do you know if there is any possibility that the unit tests will give different output? Or is it fine to just make sure that the unit tests run fine?

**Comment by paveltc** [comment]
@kiritigowda The HIP unit tests crash the system. Can you try to run them on your end to see if you can reproduce it?

**Comment by kiritigowda** [comment]
@paveltc I am noticing a few failures on this PR. @r-abishek below are some of the tests that are failing since your PR #187. Can you take a look at this?

```

test 22
      Start 22: rpp_hip_test_f16_13

22: Test command: /var/jenkins_home/workspace/main_Short-GPUOpen_rpp_develop/VVPGtw4Xe/rpp/build/release/utilities/rpp-unittests/rpp_hip_test/uniqueFunctionalities_hip "1" "0"
22: Test timeout computed to be: 1500
22: 
22: test_case 0 supports only 0 ip_bitDepth
22: ip_bitDepth = 1
22: test_case = 0
22: This functionality sub-type of tensor_transpose doesn't yet exist in RPP
22/27 Test #22: rpp_hip_test_f16_13 ..............***Failed    0.97 sec
test 23
      Start 23: rpp_hip_test_f32_14

23: Test command: /var/jenkins_home/workspace/main_Short-GPUOpen_rpp_develop/VVPGtw4Xe/rpp/build/release/utilities/rpp-unittests/rpp_hip_test/uniqueFunctionalities_hip "2" "0"
23: Test timeout computed to be: 1500
23: 
23: test_case 0 supports only 0 ip_bitDepth
23: ip_bitDepth = 2
23: test_case = 0
23: This functionality sub-type of tensor_transpose doesn't yet exist in RPP
23/27 Test #23: rpp_hip_test_f32_14 ..............***Failed    1.04 sec
test 24
      Start 24: rpp_hip_test_u08_f16_15

24: Test command: /var/jenkins_home/workspace/main_Short-GPUOpen_rpp_develop/VVPGtw4Xe/rpp/build/release/utilities/rpp-unittests/rpp_hip_test/uniqueFunctionalities_hip "3" "0"
24: Test timeout computed to be: 1500
24: 
24: test_case 0 supports only 0 ip_bitDepth
24: ip_bitDepth = 3
24: test_case = 0
24: This functionality sub-type of tensor_transpose doesn't yet exist in RPP
24/27 Test #24: rpp_hip_test_u08_f16_15 ..........***Failed    0.97 sec
test 25
      Start 25: rpp_hip_test_u08_f32_16

25: Test command: /var/jenkins_home/workspace/main_Short-GPUOpen_rpp_develop/VVPGtw4Xe/rpp/build/release/utilities/rpp-unittests/rpp_hip_test/uniqueFunctionalities_hip "4" "0"
25: Test timeout computed to be: 1500
25: 
25: test_case 0 supports only 0 ip_bitDepth
25: ip_bitDepth = 4
25: test_case = 0
25: This functionality sub-type of tensor_transpose doesn't yet exist in RPP
25/27 Test #25: rpp_hip_test_u08_f32_16 ..........***Failed    1.09 sec
test 26
      Start 26: rpp_hip_test_i08_17

26: Test command: /var/jenkins_home/workspace/main_Short-GPUOpen_rpp_develop/VVPGtw4Xe/rpp/build/release/utilities/rpp-unittests/rpp_hip_test/uniqueFunctionalities_hip "5" "0"
26: Test timeout computed to be: 1500
26: 
26: test_case 0 supports only 0 ip_bitDepth
26: ip_bitDepth = 5
26: test_case = 0
26: This functionality sub-type of tensor_transpose doesn't yet exist in RPP
26/27 Test #26: rpp_hip_test_i08_17 ..............***Failed    1.04 sec
test 27
      Start 27: rpp_hip_test_u08_i08_18

27: Test command: /var/jenkins_home/workspace/main_Short-GPUOpen_rpp_develop/VVPGtw4Xe/rpp/build/release/utilities/rpp-unittests/rpp_hip_test/uniqueFunctionalities_hip "6" "0"
27: Test timeout computed to be: 1500
27: 
27: test_case 0 supports only 0 ip_bitDepth
27: ip_bitDepth = 6
27: test_case = 0
27: This functionality sub-type of tensor_transpose doesn't yet exist in RPP
27/27 Test #27: rpp_hip_test_u08_i08_18 ..........***Failed    0.96 sec

78% tests passed, 6 tests failed out of 27

Total Test time (real) =  25.48 sec

The following tests FAILED:
	 22 - rpp_hip_test_f16_13 (Failed)
	 23 - rpp_hip_test_f32_14 (Failed)
	 24 - rpp_hip_test_u08_f16_15 (Failed)
	 25 - rpp_hip_test_u08_f32_16 (Failed)
	 26 - rpp_hip_test_i08_17 (Failed)
	 27 - rpp_hip_test_u08_i08_18 (Failed)
Errors while running CTest
```

**Comment by paveltc** [comment]
@r-abishek @kiritigowda The crash occur on the following HIP unit test:
./BatchPD_hip_pln1 /home/svcbuild/rpp-pr189/rpp/utilities/rpp-unittests/HIP_NEW/../TEST_IMAGES/three_images_224x224_src1 /home/svcbuild/rpp-pr189/rpp/utilities/rpp-unittests/HIP_NEW/../TEST_IMAGES/three_images_224x224_src2 /home/svcbuild/rpp-pr189/rpp/utilities/rpp-unittests/HIP_NEW/../OUTPUT_IMAGES_HIP_NEW/rpp_hip_pln1_advanced_augmentations 0 0 32 0

**Comment by kiritigowda** [comment]
@paveltc can we merge this pr then as it's not related to the failure? @r-abishek can we fix the tests that were turned off?

**Comment by r-abishek** [comment]
@kiritigowda Yes, this rpp_hip_pln1_advanced_augmentations 0 0 32 0 is a separate issue not stemming from PR#187. @sampath1117 Could we issue a PR to develop with the minor change?

**Comment by kiritigowda** [comment]
@paveltc - This PR currently passes all CTest - can we merge this?

```
make test
Running tests...
      Start  1: rpp_cpu_test_u08_01
 1/24 Test  #1: rpp_cpu_test_u08_01 ..............   Passed   13.79 sec
      Start  2: rpp_cpu_test_u08_02
 2/24 Test  #2: rpp_cpu_test_u08_02 ..............   Passed    0.10 sec
      Start  3: rpp_cpu_test_u08_03
 3/24 Test  #3: rpp_cpu_test_u08_03 ..............   Passed    0.07 sec
      Start  4: rpp_cpu_test_u08_04
 4/24 Test  #4: rpp_cpu_test_u08_04 ..............   Passed    0.07 sec
      Start  5: rpp_cpu_test_u08_05
 5/24 Test  #5: rpp_cpu_test_u08_05 ..............   Passed    0.07 sec
      Start  6: rpp_cpu_test_u08_06
 6/24 Test  #6: rpp_cpu_test_u08_06 ..............   Passed    0.09 sec
      Start  7: rpp_cpu_test_u08_07
 7/24 Test  #7: rpp_cpu_test_u08_07 ..............   Passed    0.07 sec
      Start  8: rpp_cpu_test_u08_08
 8/24 Test  #8: rpp_cpu_test_u08_08 ..............   Passed    0.09 sec
      Start  9: rpp_cpu_test_u08_09
 9/24 Test  #9: rpp_cpu_test_u08_09 ..............   Passed    0.07 sec
      Start 10: rpp_cpu_test_u08_11
10/24 Test #10: rpp_cpu_test_u08_11 ..............   Passed    0.07 sec
      Start 11: rpp_cpu_test_u08_12
11/24 Test #11: rpp_cpu_test_u08_12 ..............   Passed    0.07 sec
      Start 12: rpp_cpu_test_f16_13
12/24 Test #12: rpp_cpu_test_f16_13 ..............   Passed    0.07 sec
      Start 13: rpp_cpu_test_f32_14
13/24 Test #13: rpp_cpu_test_f32_14 ..............   Passed    0.07 sec
      Start 14: rpp_cpu_test_i08_15
14/24 Test #14: rpp_cpu_test_i08_15 ..............   Passed    0.07 sec
      Start 15: rpp_hip_test_u08_01
15/24 Test #15: rpp_hip_test_u08_01 ..............   Passed  102.75 sec
      Start 16: rpp_hip_test_u08_02
16/24 Test #16: rpp_hip_test_u08_02 ..............   Passed    0.42 sec
      Start 17: rpp_hip_test_u08_03
17/24 Test #17: rpp_hip_test_u08_03 ..............   Passed    0.35 sec
      Start 18: rpp_hip_test_u08_04
18/24 Test #18: rpp_hip_test_u08_04 ..............   Passed    0.41 sec
      Start 19: rpp_hip_test_u08_05
19/24 Test #19: rpp_hip_test_u08_05 ..............   Passed    0.36 sec
      Start 20: rpp_hip_test_u08_06
20/24 Test #20: rpp_hip_test_u08_06 ..............   Passed    0.38 sec
      Start 21: rpp_hip_test_u08_07
21/24 Test #21: rpp_hip_test_u08_07 ..............   Passed    0.37 sec
      Start 22: rpp_hip_test_f16_08
22/24 Test #22: rpp_hip_test_f16_08 ..............   Passed    0.38 sec
      Start 23: rpp_hip_test_f32_09
23/24 Test #23: rpp_hip_test_f32_09 ..............   Passed    0.40 sec
      Start 24: rpp_hip_test_i08_10
24/24 Test #24: rpp_hip_test_i08_10 ..............   Passed    0.38 sec

100% tests passed, 0 tests failed out of 24

Total Test time (real) = 120.95 sec
```

**Pull request merged**
